spring.application.name=gamerSupplies
server.port=8080
spring.profiles.active=dev
spring.thymeleaf.cache=false

spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Spring Data REST Base Path
spring.data.rest.base-path=/api
